config/routes.rb
Rails.application.routes.draw do
  #route home#
  root 'home#home'

  #route about#
  get "/about" => "about#about"

  #route contatos#
  get '/contatos', to: 'contatos#index'
  get '/contatos/new', to: 'contatos#new'
  post '/contatos', to: 'contatos#create'
  get '/contatos/:id', to: 'contatos#show', as: 'contato'
  get '/contatos/:id/edit', to: 'contatos#edit', as: 'edit_contato'
  patch '/contatos/:id', to: 'contatos#update'
  put '/contatos/:id', to: 'contatos#update'
  delete 'contatos/:id', to: 'contatos#delete'

  #route acessos#
  get '/acessos', to: 'acessos#index'
  # put '/users/:id/edit/', to: 'users#edit_send', as: 'edit_user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contato.rb
class Contato < ApplicationRecord
    validates_presence_of :nome, message: "O campo nome é obrigatório."
    validates_presence_of :email, message: "O campo e-mail é obrigatório."
    validates_length_of :nome, minimum: 3, message: "O nome deve ter no mínimo 3 caracteres."
    validates_length_of :email, minimum: 6, message: "O E-mail deve ter no mínimo 6 caracteres."
    validates_uniqueness_of :email, message: "O E-mail já esta cadastrado."
end

app/models/log_acessos.rb
class LogAcessos < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
    # if params[:id] && template_exists?(params[:id], ["page"])
    #   render params[:id]
    # else
    #   redirect_to '/404.html', :status => 404
    # end
  end
end

app/controllers/acessos_controller.rb
class AcessosController < ApplicationController
  def index
    # cookies[:teste] = "blonde"
    @acessos = LogAcessos.order('sysdate DESC').limit(50)
  end
end

app/controllers/application_controller.rb
require 'securerandom'

class ApplicationController < ActionController::Base
  before_action :log_acesso, :except => [:not_found]

  def set_cookies
    cookies[:uuid] = SecureRandom.uuid
  end

  def get_cookies
    if cookies[:uuid].blank?
      set_cookies
    end
  end
  # def delete_cookies
  #   cookies.delete :uuid
  # end
  def log_acesso
    get_cookies
    acesso = LogAcessos.new({:uuid => cookies[:uuid], :page => request.fullpath, :sysdate => DateTime.now})
    acesso.save!
  end
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  def index
    # cookies[:teste] = "blonde"
    @contatos = Contato.all
  end

  def new
    @contatos = Contato.new
  end

  def create
    @contatos = Contato.new(contato_params)
    @contatos.email.downcase
    @contatos.data_cadastro = DateTime.now
    if @contatos.save
      redirect_to contatos_path
    else
      render :new
    end
  end

  def update
    @contatos = Contato.find(params[:id])
    if @contatos.update(contato_params)
      redirect_to contatos_path
    else
      render :edit
    end
  end

  def edit
    @contatos = Contato.find(params[:id])
  end

  def show
    @contatos = Contato.find(params[:id])
  end

  def delete
    @contatos = Contato.find(params[:id])
    @contatos.destroy
    redirect_to contatos_path
  end

  private
    def contato_params
      params.required(:contato).permit(:nome, :email)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/about.html.erb
<section id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">About</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <ul class="timeline">
              <li>
                <div class="timeline-image">
                  <img class="rounded-circle img-fluid" src="assets/teste1.jpg" alt="">
                </div>
                <div class="timeline-panel">
                  <div class="timeline-heading">
                    <h4>2009-2011</h4>
                    <h4 class="subheading">Our Humble Beginnings</h4>
                  </div>
                  <div class="timeline-body">
                    <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>
                  </div>
                </div>
              </li>
              <li class="timeline-inverted">
                <div class="timeline-image">
                  <img class="rounded-circle img-fluid" src="assets/teste1.jpg" alt="">
                </div>
                <div class="timeline-panel">
                  <div class="timeline-heading">
                    <h4>March 2011</h4>
                    <h4 class="subheading">An Agency is Born</h4>
                  </div>
                  <div class="timeline-body">
                    <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>
                  </div>
                </div>
              </li>
              <li>
                <div class="timeline-image">
                  <img class="rounded-circle img-fluid" src="assets/teste1.jpg" alt="">
                </div>
                <div class="timeline-panel">
                  <div class="timeline-heading">
                    <h4>December 2012</h4>
                    <h4 class="subheading">Transition to Full Service</h4>
                  </div>
                  <div class="timeline-body">
                    <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>
                  </div>
                </div>
              </li>
              <li class="timeline-inverted">
                <div class="timeline-image">
                  <img class="rounded-circle img-fluid" src="assets/teste1.jpg" alt="">
                </div>
                <div class="timeline-panel">
                  <div class="timeline-heading">
                    <h4>July 2014</h4>
                    <h4 class="subheading">Phase Two Expansion</h4>
                  </div>
                  <div class="timeline-body">
                    <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>
                  </div>
                </div>
              </li>
              <li class="timeline-inverted">
                <div class="timeline-image">
                  <h4>Be Part
                    <br>Of Our
                    <br>Story!</h4>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>

app/views/acessos/index.html.erb
<div class="container">
  <div class="title-container">
    <h2>Controle de Acesso</h2>
  </div>
  <div class="tbl-header">
    <table>
      <thead>
        <!-- <th>id do Usuário</th> -->
        <th>Linhas</th>
        <th>UUID</th>
        <th>Pagina</th>
        <th>Data Acesso</th>
      </thead>
    </table>
  </div>
    <div class="tbl-content">
      <table>
        <tbody>
          <% @acessos.each_with_index do |acesso,index| %>
            <tr>
              <td><%= index+1 %></td>
              <th scope="row"><%= acesso.uuid %></th>
              <td><%= acesso.page %></td>
              <td><%= acesso.sysdate.strftime("%d/%m/%Y - %H:%M") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/contatos/edit.html.erb
<script type="text/javascript">
	$(function(){
		$("#testForm").submit(function(event) {
			if (!validaNome($('#nome').val())){
				return false;
			}

			if (!validaEmail($('#email').val())){
				return false;
			}
			return true;
		});
	})
</script>
<div class="container">
  <div class="title-container">
    <h2>Editar</h2>
  </div>
  <div class="form-new">
    <%= form_for @contatos , :html => { :id => "testForm" } do |c| %>
      <div class="form-group">
        <%= c.label :nome %>
        <%= c.text_field :nome, class: "form-control", id:"nome" %>
      </div>
      <div class="form-group">
        <%= c.label :email %>
        <%= c.text_field :email, class: "form-control", type: "email", id:"email" %>
      </div>
      <div class="actions">
        <%= c.submit "Salvar", class: "btn btn-primary" %>
      </div>
			<% if @contatos.errors.any? %>
				<div id="error_explanation">
					<ul>
						<% @contatos.errors.each do |title,message| %>
							<li><%= message %></li>
						<% end %>
					</ul>
				</div>
			<% end %>
    <% end %>
  </div>
</div>

app/views/contatos/index.html.erb
<div class="container">
  <div class="title-container">
    <h2>Lista de Contatos</h2>
  </div>
  <div class="tbl-header">
    <table>
      <thead>
        <!-- <th>id do Usuário</th> -->
        <th>Nome</th>
        <th>E-mail</th>
        <th>Data Cadastro</th>
        <th>Ações</th>
      </thead>
    </table>
  </div>
    <div class="tbl-content">
      <table>
        <tbody>
          <% @contatos.each do |contato| %>
            <tr>
              <!-- <th scope="row"><%= contato.id %></th> -->
              <th scope="row"><%= contato.nome %></th>
              <td><%= contato.email %></td>
              <td><%= contato.data_cadastro.strftime("%d/%m/%Y - %H:%M") %></td>
              <td>
                <!-- <%= link_to "Visualizar", contato_path(contato), class: "badge badge-info" %> -->
                <%= link_to "Editar", edit_contato_path(contato), class: "badge badge-warning" %>
                <%= link_to "Excluir", contato, method: :delete, data: {confirm: "Deseja excluir este contato?"},  class: "badge badge-danger" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/contatos/new.html.erb
<script type="text/javascript">
	$(function(){
		$("#testForm").submit(function(event) {
			if (!validaNome($('#nome').val())){
				return false;
			}

			if (!validaEmail($('#email').val())){
				return false;
			}
			return true;
		});
	})
</script>
<div class="container">
  <div class="title-container">
    <h2>Contato</h2>
  </div>
  <div class="form-new">
    <%= form_for @contatos, :html => { :id => "testForm" } do |c| %>
      <div class="form-group">
        <%= c.label :nome %>
        <%= c.text_field :nome, class: "form-control", placeholder: "Nome", id: "nome" %>
      </div>
      <div class="form-group">
        <%= c.label :email %>
        <%= c.text_field :email, class: "form-control", placeholder: "E-mail", type: "email", id:"email"%>
      </div>
      <div class="actions">
        <%= c.submit "Salvar", class: "btn btn-primary" %>
      </div>
			<% if @contatos.errors.any? %>
				<div id="error_explanation">
					<ul>
						<% @contatos.errors.each do |title,message| %>
							<li><%= message %></li>
						<% end %>
					</ul>
				</div>
			<% end %>
    <% end %>
  </div>
</div>

app/views/contatos/show.html.erb
<h1>show</h1>

app/views/home/home.html.erb
<header class="masthead">
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in">Welcome To My Test!</div>
      <div class="intro-heading text-uppercase">It's Nice To Meet You</div>
      <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="/contatos/new">Leave Your Contact</a>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teste</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head%>
  </head>

  <body id="page-top">
    <nav class="navbar navbar-expand-lg navbar-dark" id="mainNav">
          <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="/acessos">Teste iCasei</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              Menu
              <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav text-uppercase ml-auto">
                <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" href="/">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" href="/about">Sobre</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" href="/contatos/new">Contato</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" href="/contatos">Lista de Contatos</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link js-scroll-trigger" href="/acessos">Controle de Acesso</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

    <!-- <nav class="navbar navbar-expand-lg navbar-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Sobre</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/contatos/new">Contato</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/contatos">Lista de Contatos</a>
          </li>
        </ul>
      </div>
    </nav> -->
    <%= yield %>

    <!-- <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <span class="copyright">Copyright &copy; Your Website 2018</span>
          </div>
          <div class="col-md-4">
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="#">
                  <i class="fab fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fab fa-facebook-f"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fab fa-linkedin-in"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="col-md-4">
            <ul class="list-inline quicklinks">
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer> -->
  </body>
</html>